### ISSUE TITLE
Interesting

### ISSUE THREAD

**Issue by clozinski** [jimfulton/pheather#1]
But not at all clear to me what is going on under the hood.  The Panda is a Python object which refers to a C data structure.  When you go to save it to the file system, does it save it as a ByteArray?  Probably yes.  Probably quite efficient.  But good to spell it out.

**Comment by jimfulton** [comment]
phether saves a pandas data set as a blob in feather format, https://blog.cloudera.com/blog/2016/03/feather-a-fast-on-disk-format-for-data-frames-for-r-and-python-powered-by-apache-arrow/.
